-- 1. 기존 테이블이 존재할 경우 삭제 (순서 주의: 외래키 의존성)
DROP TABLE IF EXISTS student_submissions;
DROP TABLE IF EXISTS questions;

-- 2. 질문(문제 템플릿) 테이블 생성
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit VARCHAR(100) NOT NULL,               -- 단원 분류 (예: 힘과 운동, 전자기, 열역학)
    title VARCHAR(200) NOT NULL,              -- 문제 제목
    template_text TEXT NOT NULL,              -- 문제 템플릿 텍스트 ({변수명}으로 표시)
    variable_config JSONB NOT NULL,           -- 랜덤 생성할 변수들의 범위 정보
    answer_formula TEXT NOT NULL,             -- 정답을 계산할 JS 수식 텍스트 (예: force / mass)
    unit_symbol VARCHAR(50) NOT NULL,         -- 정답의 단위 (예: m/s², N, V)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 학생 제출(채점 결과) 테이블 생성
CREATE TABLE student_submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    student_name VARCHAR(100) NOT NULL,       -- 학생 이름
    student_number VARCHAR(50) NOT NULL,      -- 학생 학번 (예: 30101)
    unit VARCHAR(100) NOT NULL,               -- 단원 분류
    question_id BIGINT REFERENCES questions(id) ON DELETE CASCADE, -- 연결된 문제 ID
    variables JSONB NOT NULL,                 -- 해당 학생에게 할당되었던 수치 값 (JSON)
    submitted_answer NUMERIC NOT NULL,        -- 학생이 제출한 답안
    correct_answer NUMERIC NOT NULL,          -- 계산된 실제 정답
    is_correct BOOLEAN NOT NULL,              -- 정답 여부 (true/false)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 예시 물리 문제 데이터 삽입
INSERT INTO questions (unit, title, template_text, variable_config, answer_formula, unit_symbol)
VALUES
  (
    '힘과 운동',
    '뉴턴 제2법칙 (가속도 구하기)',
    '마찰이 없는 수평면 위에 놓인 질량 {mass} kg의 물체에 {force} N의 일정한 힘을 수평 방향으로 가했습니다. 이때 물체의 가속도의 크기는 얼마인가요?',
    '{"mass": {"min": 2, "max": 10, "step": 1}, "force": {"min": 10, "max": 50, "step": 5}}',
    'force / mass',
    'm/s²'
  ),
  (
    '힘과 운동',
    '운동량과 충격량',
    '질량 {mass} kg인 축구공이 {velocity_1} m/s의 속도로 날아가다가 발에 맞고 반대 방향으로 {velocity_2} m/s의 속도로 튕겨 나갔습니다. 이때 발이 축구공에 가한 충격량의 크기는 얼마인가요?',
    '{"mass": {"min": 0.4, "max": 0.8, "step": 0.1}, "velocity_1": {"min": 10, "max": 20, "step": 2}, "velocity_2": {"min": 15, "max": 25, "step": 1}}',
    'mass * (velocity_1 + velocity_2)',
    'N·s'
  ),
  (
    '전자기',
    '옴의 법칙 (전류 구하기)',
    '저항이 {resistance} Ω인 전구에 {voltage} V의 전압을 걸었을 때, 전선에 흐르는 전류의 세기는 몇 A인가요?',
    '{"resistance": {"min": 5, "max": 20, "step": 5}, "voltage": {"min": 10, "max": 100, "step": 10}}',
    'voltage / resistance',
    'A'
  ),
  (
    '전자기',
    '전력 소모량',
    '{voltage} V의 전원에 연결하여 {current} A의 전류가 흐르는 가전제품의 소비 전력은 몇 W인가요?',
    '{"voltage": {"min": 110, "max": 220, "step": 110}, "current": {"min": 2, "max": 10, "step": 1}}',
    'voltage * current',
    'W'
  );

-- 5. 누구나 조회 및 삽입이 가능하도록 RLS(행 보안 정책) 비활성화 또는 단순 허용 정책 적용
-- (교육 연구용 목적이므로 복잡한 정책 설정 대신 읽기/쓰기를 모두 허용합니다.)
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_submissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read to questions" ON questions
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert to submissions" ON student_submissions
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow public read to submissions" ON student_submissions
    FOR SELECT TO public USING (true);
